trigger:
  branches:
    include:
      - main  # Replace with your branch

pr:
  branches:
    include:
      - main  # Replace with your branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: docker-registry-variable
  - name: imageName
    value: 'crudapp'  # Replace with your app's name

stages:
- stage: Build
  displayName: 'Build stage'
  jobs:
  - job: Build
    displayName: 'Build job'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'xmen-connection'  # Replace with your Azure subscription service connection
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo $(Build.BuildId)
          az acr build --registry viper --image $(imageName):$(Build.BuildId) .

    - script: |
        mkdir -p $(Pipeline.Workspace)/output
        echo "Sample build output" > $(Pipeline.Workspace)/output/sample.txt
        echo "Build directory contents:"
        ls -la $(Pipeline.Workspace)
        echo "Output directory contents:"
        ls -la $(Pipeline.Workspace)/output
      displayName: 'Create Output Directory and Generate Dummy File'

    - script: |
        cd $(Pipeline.Workspace)/output
        zip -r artifact.zip *
        echo "ZIP file created:"
        ls -la $(Pipeline.Workspace)/output
      displayName: 'Create ZIP file of build output'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)/output'
        artifact: 'drop'
        publishLocation: 'pipeline'

- stage: Deploy
  displayName: 'Deploy stage'
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: 'Deploy job'
    steps:
    - download: current
      artifact: 'drop'

    - script: |
        unzip $(Pipeline.Workspace)/drop/artifact.zip -d $(Pipeline.Workspace)/drop
        echo "Artifact contents:"
        ls -la $(Pipeline.Workspace)/drop
      displayName: 'Unzip Artifact'

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'xmen-connection'  # Replace with your Azure subscription service connection
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az webapp config container set --name crudapp1 --resource-group crudapp --docker-custom-image-name viper.azurecr.io/$(imageName):$(Build.BuildId) --docker-registry-server-url https://viper.azurecr.io --docker-registry-server-user $(dockerRegistryUsername) --docker-registry-server-password $(dockerRegistryPassword)
        addSpnToEnvironment: true

    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'xmen-connection'  # Replace with your Azure subscription service connection
        appName: 'crudapp1'  # Replace with your app service name
        resourceGroupName: 'crudapp'  # Replace with your resource group name
        deployToSlotOrASE: false
        dockerNamespace: 'viper.azurecr.io'
        dockerRepository: $(imageName)
        dockerImageTag: $(Build.BuildId)
        startupCommand: ''

resources:
  containers:
  - container: azurecli
    image: mcr.microsoft.com/azure-cli
    endpoint: xmen-registry
