name: Build, Push, and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo ${{ secrets.REGISTRY_PASSWORD }} | docker login -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

    - name: Build the Docker image
      run: docker build -t ${{ secrets.REGISTRY_USERNAME }}/smart-crud:${{ github.sha }} .

    - name: Push the Docker image to Docker Hub
      run: docker push ${{ secrets.REGISTRY_USERNAME }}/smart-crud:${{ github.sha }}

    - name: Set up Azure CLI
      uses: azure/setup-azure-cli@v1

    - name: Log in to Azure
      run: az login --service-principal -u ${{ secrets.AZURE_CREDENTIALS.clientId }} -p ${{ secrets.AZURE_CREDENTIALS.clientSecret }} --tenant ${{ secrets.AZURE_CREDENTIALS.tenantId }}

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: smart-crud-dev
        images: ${{ secrets.REGISTRY_USERNAME }}/smart-crud:${{ github.sha }}

